### ISSUE TITLE
Error when running script: No JSON object could be decoded

### ISSUE THREAD

**Issue by pakjiddat** [inequation/trello2redmine#1]
Hi,

I tried to run your script but I get an error. Please see attached screenshot.

Regards,
Nadir Latif
![screenshot from 2017-01-11 17 50 11](https://cloud.githubusercontent.com/assets/20923812/21849222/7d364bc4-d826-11e6-9dc4-c17b243295ab.png)

**Comment by inequation** [comment]
This error means that the script could not obtain the Trello board's JSON. Is your Trello board publicy available? If not, you may need to either add authentication code to the script (which I didn't bother to do), or make the board temporarily publicly accessible.

You may test it by opening your Trello board link suffixed by `.json` in a private mode browser window, e.g. `https://trello.com/b/gHooNW9I.json` displays the Unreal Engine's road map Trello board's JSON.

**Comment by pakjiddat** [comment]
That fixed the error. But when I ran the script with the command: **python trello2redmine.py -c** it said: "Making a dry run! Re-run with -c to commit the import into Redmine". I got the script to work by replacing the line: dry_run = len(sys.argv) < 3 or sys.argv[2] != '-c' with dry_run = len(sys.argv) < 2 or sys.argv[1] != '-c' in  trello2redmine.py

**Comment by inequation** [comment]
You're right! Fixed in 6e5358e6a119ef7c699ae51b974a092ba4807b3c. Thanks!
